### ISSUE TITLE
Peer-to-peer-code-review

### ISSUE THREAD

**Issue by KenbonT** [miltonHenschel/myPortfolio#14]
▶️ You made a beautiful website.
▶️  Your code is clean.
       Constructive comments
▶️ Kindly work on your tablet view to fit the screen. Because your website needs to be compatible with tablet users as well.  
▶️ For the laptop view, kindly work on your social icons. Because your page would be better if you adjust the height and width of the icons.

**Comment by miltonHenschel** [comment]
Thanks, guys! Will do...
